# Generated by Django 5.1.5 on 2025-02-12 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0001_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentinchargeandhod',
            name='hod',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hod_records', to='staff.staffprofile'),
        ),
        migrations.AddField(
            model_name='departmentinchargeandhod',
            name='incharge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incharge_records', to='staff.staffprofile'),
        ),
        migrations.AddField(
            model_name='departments',
            name='hod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hod_departments', to='staff.staffprofile'),
        ),
        migrations.AddField(
            model_name='departments',
            name='incharge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incharge_departments', to='staff.staffprofile'),
        ),
        migrations.AddField(
            model_name='departmentinchargeandhod',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incharge_and_hod_records', to='administration.departments'),
        ),
        migrations.AddField(
            model_name='designations',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='designations', to='administration.departments'),
        ),
        migrations.AddIndex(
            model_name='departments',
            index=models.Index(fields=['name'], name='administrat_name_15fa14_idx'),
        ),
        migrations.AddIndex(
            model_name='departments',
            index=models.Index(fields=['short_code'], name='administrat_short_c_7cfe61_idx'),
        ),
        migrations.AddIndex(
            model_name='departmentinchargeandhod',
            index=models.Index(fields=['department'], name='administrat_departm_3a5e2b_idx'),
        ),
        migrations.AddIndex(
            model_name='designations',
            index=models.Index(fields=['department'], name='administrat_departm_ba18db_idx'),
        ),
        migrations.AddIndex(
            model_name='designations',
            index=models.Index(fields=['name'], name='administrat_name_acde1c_idx'),
        ),
    ]
