# Generated by Django 5.1.5 on 2025-02-12 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='emp_id',
            field=models.CharField(db_index=True, default=0, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
