# Generated by Django 5.1.5 on 2025-02-12 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_staffprofile_emp_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffprofile',
            old_name='is_teaching_staff',
            new_name='is_hosteller',
        ),
    ]
