# Generated by Django 5.1.5 on 2025-02-13 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_alter_staffprofile_blood_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True),
        ),
    ]
