# Generated by Django 5.1.5 on 2025-02-13 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0002_alter_hostel_incharge'),
        ('staff', '0006_alter_staffprofile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='hostel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hostel_staff', to='hostel.hostel'),
        ),
    ]
