# Generated by Django 5.1.5 on 2025-02-13 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0006_alter_staffprofile_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('incharge', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.staffprofile', verbose_name='Incharge')),
            ],
            options={
                'verbose_name': 'Hostel',
                'verbose_name_plural': 'Hostels',
                'indexes': [models.Index(fields=['name'], name='hostel_host_name_617ba9_idx'), models.Index(fields=['incharge'], name='hostel_host_incharg_d1d86a_idx'), models.Index(fields=['created_on'], name='hostel_host_created_7a772f_idx'), models.Index(fields=['updated_on'], name='hostel_host_updated_499820_idx')],
            },
        ),
    ]
