# Generated by Django 5.1.5 on 2025-02-13 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0001_initial'),
        ('staff', '0006_alter_staffprofile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostel',
            name='incharge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='managed_hostel', to='staff.staffprofile', verbose_name='Incharge'),
        ),
    ]
