# Generated by Django 5.1.5 on 2025-02-13 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0002_hostel_capacity_hostel_wardens'),
        ('staff', '0006_alter_staffprofile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostel',
            name='wardens',
            field=models.ManyToManyField(blank=True, related_name='hostels', to='staff.staffprofile', verbose_name='Wardens'),
        ),
    ]
