# Generated by Django 5.1.5 on 2025-02-13 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0002_alter_hostel_incharge'),
        ('hostel', '0003_alter_hostel_wardens'),
    ]

    operations = [
    ]
