# Generated by Django 5.1.5 on 2025-02-13 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0004_merge_20250213_2046'),
        ('staff', '0008_staffprofile_room_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostel',
            name='incharge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hostel_incharge', to='staff.staffprofile', verbose_name='Incharge'),
        ),
    ]
