# Generated by Django 5.1.5 on 2025-02-19 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0005_alter_hostel_incharge'),
        ('staff', '0008_staffprofile_room_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostel',
            name='incharge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hostel_incharge', to='staff.staffprofile', verbose_name='Incharge'),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='wardens',
            field=models.ManyToManyField(blank=True, null=True, related_name='hostels', to='staff.staffprofile', verbose_name='Wardens'),
        ),
    ]
