# Generated by Django 5.1.5 on 2025-02-19 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0006_alter_hostel_incharge_alter_hostel_wardens'),
        ('staff', '0008_staffprofile_room_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostel',
            name='wardens',
            field=models.ManyToManyField(blank=True, related_name='hostels', to='staff.staffprofile', verbose_name='Wardens'),
        ),
    ]
