# Generated by Django 5.1.5 on 2025-02-11 13:55

import django.db.models.deletion
import django_tenants.postgresql_backend.base
import utils.multis3
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('schema_name', models.CharField(db_index=True, max_length=63, unique=True, validators=[django_tenants.postgresql_backend.base._check_schema_name])),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=253, unique=True)),
                ('is_primary', models.BooleanField(db_index=True, default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='app.client')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Organizations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(db_index=True, max_length=550, unique=True)),
                ('address', models.TextField()),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('email_domain', models.CharField(blank=True, max_length=50, null=True)),
                ('hr_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('staff_group_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('management_group_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('suggestions_emails', models.TextField(blank=True, null=True)),
                ('hr_mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('short_code', models.CharField(db_index=True, max_length=10, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, storage=utils.multis3.TenantMediaStorage(), upload_to='Organizations/Logo/')),
                ('email_banner', models.ImageField(blank=True, null=True, storage=utils.multis3.TenantMediaStorage(), upload_to='Organizations/Email_Banner/')),
                ('org_connect_domain', models.CharField(db_index=True, default='Connect Domain not added!', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='organization', to='app.client')),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
                'indexes': [models.Index(fields=['uuid'], name='app_organiz_uuid_26669c_idx'), models.Index(fields=['name'], name='app_organiz_name_81b1ad_idx'), models.Index(fields=['short_code'], name='app_organiz_short_c_f6567e_idx')],
            },
        ),
    ]
