# Generated by Django 5.1.5 on 2025-02-18 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect_bills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappbill',
            name='wa_response',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
