# Generated by Django 5.1.5 on 2025-02-18 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect_bills', '0002_whatsappbill_wa_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappbill',
            name='wa_response',
            field=models.TextField(blank=True, null=True, verbose_name=''),
        ),
    ]
