# Generated by Django 5.1.5 on 2025-02-19 10:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect_bills', '0003_alter_whatsappbill_wa_response'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_by', models.CharField(max_length=255, null=True)),
                ('subject', models.CharField(max_length=255)),
                ('recipient', models.EmailField(max_length=254)),
                ('cc_emails', models.TextField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(default='Pending', max_length=200)),
                ('task_id', models.CharField(default='Main Thread', max_length=250)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
