# Generated by Django 5.1.5 on 2025-02-12 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='is_school_admin',
            new_name='is_hospital_admin',
        ),
    ]
